### PR TITLE
Fix README.md installation example to accurate parse out browser_down…

### PR DESCRIPTION
**Pull request by icedawn**
# Pull Request

### Problem(s)
README.md installation example script fails to correctly parse the browser_download_url.

### Changes
Fixed up the sed command to parse the browser_download_url correctly.

### Context
This is only pertinent for users installing via the "latest" script method.

### CODE REVIEW

**Comment by mayankk2308** [comment]
I don't see an issue with the current command, it seems to provide the appropriate download URL in question.

**Comment by mayankk2308** [comment]
The command you provide works, but semantically incorrect. With your command, `xargs` passes two arguments to `curl`, one being the `browser_download_url` string, and the other the actual URL. So first, `curl` fails to fetch anything fails silently, and then attempts to fetch from the second string/arg, which works and the script is downloaded.

**Comment by icedawn** [comment]
When I run this ...
```shell
curl -s "https://api.github.com/repos/mayankk2308/purge-wrangler/releases/latest" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/'
```

I get this ...
```shell
This release includes minor fixes.
```

**Comment by icedawn** [comment]
The response I get from curl looks like this ...
```
{"url":"https://api.github.com/repos/mayankk2308/purge-wrangler/releases/14546769","assets_url":"https://api.github.com/repos/mayankk2308/purge-wrangler/releases/14546769/assets","upload_url":"https://uploads.github.com/repos/mayankk2308/purge-wrangler/releases/14546769/assets{?name,label}","html_url":"https://github.com/mayankk2308/purge-wrangler/releases/tag/5.1.1","id":14546769,"node_id":"MDc6UmVsZWFzZTE0NTQ2NzY5","tag_name":"5.1.1","target_commitish":"master","name":"5.1.1","draft":false,"author":{"login":"mayankk2308","id":11367902,"node_id":"MDQ6VXNlcjExMzY3OTAy","avatar_url":"https://avatars0.githubusercontent.com/u/11367902?v=4","gravatar_id":"","url":"https://api.github.com/users/mayankk2308","html_url":"https://github.com/mayankk2308","followers_url":"https://api.github.com/users/mayankk2308/followers","following_url":"https://api.github.com/users/mayankk2308/following{/other_user}","gists_url":"https://api.github.com/users/mayankk2308/gists{/gist_id}","starred_url":"https://api.github.com/users/mayankk2308/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mayankk2308/subscriptions","organizations_url":"https://api.github.com/users/mayankk2308/orgs","repos_url":"https://api.github.com/users/mayankk2308/repos","events_url":"https://api.github.com/users/mayankk2308/events{/privacy}","received_events_url":"https://api.github.com/users/mayankk2308/received_events","type":"User","site_admin":false},"prerelease":false,"created_at":"2018-12-14T20:52:37Z","published_at":"2018-12-14T20:55:06Z","assets":[{"url":"https://api.github.com/repos/mayankk2308/purge-wrangler/releases/assets/10158381","id":10158381,"node_id":"MDEyOlJlbGVhc2VBc3NldDEwMTU4Mzgx","name":"purge-wrangler.sh","label":null,"uploader":{"login":"mayankk2308","id":11367902,"node_id":"MDQ6VXNlcjExMzY3OTAy","avatar_url":"https://avatars0.githubusercontent.com/u/11367902?v=4","gravatar_id":"","url":"https://api.github.com/users/mayankk2308","html_url":"https://github.com/mayankk2308","followers_url":"https://api.github.com/users/mayankk2308/followers","following_url":"https://api.github.com/users/mayankk2308/following{/other_user}","gists_url":"https://api.github.com/users/mayankk2308/gists{/gist_id}","starred_url":"https://api.github.com/users/mayankk2308/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mayankk2308/subscriptions","organizations_url":"https://api.github.com/users/mayankk2308/orgs","repos_url":"https://api.github.com/users/mayankk2308/repos","events_url":"https://api.github.com/users/mayankk2308/events{/privacy}","received_events_url":"https://api.github.com/users/mayankk2308/received_events","type":"User","site_admin":false},"content_type":"application/x-sh","state":"uploaded","size":46156,"download_count":6124,"created_at":"2018-12-14T20:55:04Z","updated_at":"2018-12-14T20:55:04Z","browser_download_url":"https://github.com/mayankk2308/purge-wrangler/releases/download/5.1.1/purge-wrangler.sh"}],"tarball_url":"https://api.github.com/repos/mayankk2308/purge-wrangler/tarball/5.1.1","zipball_url":"https://api.github.com/repos/mayankk2308/purge-wrangler/zipball/5.1.1","body":"This release includes minor fixes."}
```

**Comment by mayankk2308** [comment]
screen shot 2019-02-12 at 11 24 43 pm
As you can see in the screenshot, with the same command, I am getting the correct output. If you look at the api results in a browser window, and in that window search for browser_download_url, there is only one instance. Clearly the **grep** is capturing that instance. I am not sure what the issue is on your end, but no one has ever had this issue (the script is downloaded 50-100 times a day sometimes).

**Comment by icedawn** [comment]
That is the problem:  on one of my Macs I'm getting a single line back from curl, while on another it's multiple lines.  I'll debug it -- must be a different version of curl or a configuration option.

**Comment by mayankk2308** [comment]
@icedawn thank you for confirming. At least this brings up a need for me to consider different variations of binaries. Does specifying /usr/bin/curl on the offending Mac make a difference to your output?

**Comment by icedawn** [comment]
@mayankk2308 no problem!  thank you for this great tool!

Ok, you nailed it.  So the problem turns out to be my ~/.curlrc file on the machine showing the problem.  It contains the following:

```
# Disguise as IE 9 on Windows 7.
user-agent = "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"

# When following a redirect, automatically set the previous URL as referer.
referer = ";auto"

# Wait 60 seconds before timing out.
connect-timeout = 60
```
The user-agent override is what causes the difference in the server response.  That's probably been there for years on this machine.  Removing that line or deleting the .curlrc file entirely fixes the problem.

There's a space between the key/value in the multiline case.  I've checked in a regex patch that works with both multiline and single line.  I'll send you another pull request so you can check it out.

**Pull request closed without merging**
